consistent usage of spaces instead of mixed tab/space to avoid mingw v7.3 compiler issue, see #252, e.g.
UTCP/src/ftp_c.cpp: In member function ‘virtual int CUT_FTPClient::ReceiveFile(CUT_DataSource&, LPCSTR)’:
UTCP/src/ftp_c.cpp:332:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if ( m_nFirewallMode )
     ^~
UTCP/src/ftp_c.cpp:335:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  m_wsData.SSLSetReuseSession(SSLGetCurrentSession());