reverted update travis image from trusty -> xenial due to link issues: [ 50%] Linking C shared library libssh.dll CMakeFiles/ssh_shared.dir/objects.a(pthread.c.obj):pthread.c:(.text+0x4e): undefined reference to `pthread_mutex_init' CMakeFiles/ssh_shared.dir/objects.a(pthread.c.obj):pthread.c:(.text+0x99): undefined reference to `pthread_mutex_destroy' CMakeFiles/ssh_shared.dir/objects.a(pthread.c.obj):pthread.c:(.text+0xca): undefined reference to `pthread_mutex_lock' CMakeFiles/ssh_shared.dir/objects.a(pthread.c.obj):pthread.c:(.text+0xdf): undefined reference to `pthread_mutex_unlock' CMakeFiles/ssh_shared.dir/objects.a(pthread.c.obj):pthread.c:(.text+0xec): undefined reference to `pthread_self' CMakeFiles/ssh_shared.dir/objects.a(pthread.c.obj):pthread.c:(.text+0x111): undefined reference to `pthread_mutex_lock' CMakeFiles/ssh_shared.dir/objects.a(pthread.c.obj):pthread.c:(.text+0x14b): undefined reference to `pthread_mutex_unlock'